# Generated by Django 6.1.1 on 2026-09-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_manufacturer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
    ]
